# Generated by Django 3.0.3 on 2020-02-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='address_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('data', models.CharField(max_length=200)),
            ],
        ),
    ]
